const KEY="carepath:accessibility:v3";
const LANG_KEY="carepath:language:v3";
const defaults={size:"normal",contrast:false,motion:false,underline:false};
const labels={en:{access:"Accessibility",language:"Language",voice:"Read aloud"},hi:{access:"सुलभता",language:"भाषा",voice:"पढ़कर सुनाएँ"},kn:{access:"ಪ್ರವೇಶಸಾಧ್ಯತೆ",language:"ಭಾಷೆ",voice:"ಓದಿ ಕೇಳಿಸಿ"}};
const translations={
hi:{"PUBLIC SERVICE JOURNEY LAYER":"सार्वजनिक सेवा यात्रा","One journey.":"एक यात्रा।","Any service.":"कोई भी सेवा।","CarePath helps people understand which official service to use, what to prepare, and what to do next — without replacing the government system.":"CarePath लोगों को सही सरकारी सेवा चुनने, तैयारी समझने और अगला कदम जानने में मदद करता है — सरकारी व्यवस्था को बदले बिना।","Start with what you need.":"अपनी ज़रूरत से शुरू करें।","Choose a service and CarePath will guide the journey in plain language.":"एक सेवा चुनें और CarePath आपको आसान भाषा में पूरी प्रक्रिया बताएगा।","Healthcare":"स्वास्थ्य सेवा","Appointments, hospital visits and tests":"अपॉइंटमेंट, अस्पताल की यात्रा और जाँच","I need healthcare":"मुझे स्वास्थ्य सेवा चाहिए","Working prototype":"कार्यशील प्रोटोटाइप","Pension":"पेंशन","Understand eligibility and application steps":"पात्रता और आवेदन के चरण समझें","I need pension help":"मुझे पेंशन में मदद चाहिए","Journey design":"यात्रा डिज़ाइन","Certificates":"प्रमाणपत्र","Know which certificate service to use":"जानें कौन-सी प्रमाणपत्र सेवा इस्तेमाल करनी है","I need a certificate":"मुझे प्रमाणपत्र चाहिए","Grievances":"शिकायतें","Understand how to report a public-service problem":"जानें सार्वजनिक सेवा की समस्या कैसे दर्ज करें","I need to report a problem":"मुझे समस्या दर्ज करनी है","Find the right service":"सही सेवा खोजें","Understand the official process":"सरकारी प्रक्रिया समझें","Know your next step":"अपना अगला कदम जानें","Any device, low connectivity":"कोई भी डिवाइस, कम इंटरनेट","Accessibility options":"सुलभता विकल्प","Adjust CarePath to make the journey easier to read, see and use.":"CarePath को पढ़ने, देखने और इस्तेमाल करने में आसान बनाने के लिए विकल्प चुनें।","Normal text":"सामान्य टेक्स्ट","Larger text":"बड़ा टेक्स्ट","Extra-large text":"बहुत बड़ा टेक्स्ट","High contrast":"उच्च कंट्रास्ट","Reduce motion":"एनीमेशन कम करें","Underline links":"लिंक के नीचे रेखा","Reset settings":"सेटिंग रीसेट करें"},
kn:{"PUBLIC SERVICE JOURNEY LAYER":"ಸಾರ್ವಜನಿಕ ಸೇವಾ ಪ್ರಯಾಣ","One journey.":"ಒಂದು ಪ್ರಯಾಣ.","Any service.":"ಯಾವುದೇ ಸೇವೆ.","CarePath helps people understand which official service to use, what to prepare, and what to do next — without replacing the government system.":"CarePath ಯಾವ ಸರ್ಕಾರಿ ಸೇವೆ ಬಳಸಬೇಕು, ಏನು ಸಿದ್ಧಪಡಿಸಬೇಕು ಮತ್ತು ಮುಂದೇನು ಮಾಡಬೇಕು ಎಂಬುದನ್ನು ಸರಳವಾಗಿ ತಿಳಿಸುತ್ತದೆ — ಸರ್ಕಾರಿ ವ್ಯವಸ್ಥೆಯನ್ನು ಬದಲಾಯಿಸದೆ.","Start with what you need.":"ನಿಮಗೆ ಬೇಕಾದುದರಿಂದ ಪ್ರಾರಂಭಿಸಿ.","Choose a service and CarePath will guide the journey in plain language.":"ಒಂದು ಸೇವೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ. CarePath ಸರಳ ಭಾಷೆಯಲ್ಲಿ ಮುಂದಿನ ಹಂತಗಳನ್ನು ತೋರಿಸುತ್ತದೆ.","Healthcare":"ಆರೋಗ್ಯ ಸೇವೆ","Appointments, hospital visits and tests":"ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು, ಆಸ್ಪತ್ರೆ ಭೇಟಿ ಮತ್ತು ಪರೀಕ್ಷೆಗಳು","I need healthcare":"ನನಗೆ ಆರೋಗ್ಯ ಸೇವೆ ಬೇಕು","Working prototype":"ಕಾರ್ಯನಿರ್ವಹಿಸುವ ಮಾದರಿ","Pension":"ಪಿಂಚಣಿ","Understand eligibility and application steps":"ಅರ್ಹತೆ ಮತ್ತು ಅರ್ಜಿ ಹಂತಗಳನ್ನು ತಿಳಿಯಿರಿ","I need pension help":"ನನಗೆ ಪಿಂಚಣಿ ಸಹಾಯ ಬೇಕು","Journey design":"ಪ್ರಯಾಣ ವಿನ್ಯಾಸ","Certificates":"ಪ್ರಮಾಣಪತ್ರಗಳು","Know which certificate service to use":"ಯಾವ ಪ್ರಮಾಣಪತ್ರ ಸೇವೆ ಬಳಸಬೇಕು ಎಂದು ತಿಳಿಯಿರಿ","I need a certificate":"ನನಗೆ ಪ್ರಮಾಣಪತ್ರ ಬೇಕು","Grievances":"ದೂರುಗಳು","Understand how to report a public-service problem":"ಸಾರ್ವಜನಿಕ ಸೇವೆಯ ಸಮಸ್ಯೆಯನ್ನು ಹೇಗೆ ವರದಿ ಮಾಡಬೇಕು ಎಂದು ತಿಳಿಯಿರಿ","I need to report a problem":"ನಾನು ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಬೇಕು","Find the right service":"ಸರಿಯಾದ ಸೇವೆಯನ್ನು ಹುಡುಕಿ","Understand the official process":"ಅಧಿಕೃತ ಪ್ರಕ್ರಿಯೆಯನ್ನು ತಿಳಿಯಿರಿ","Know your next step":"ಮುಂದಿನ ಹಂತವನ್ನು ತಿಳಿಯಿರಿ","Any device, low connectivity":"ಯಾವುದೇ ಸಾಧನ, ಕಡಿಮೆ ಸಂಪರ್ಕ","Accessibility options":"ಪ್ರವೇಶಸಾಧ್ಯತೆ ಆಯ್ಕೆಗಳು","Adjust CarePath to make the journey easier to read, see and use.":"CarePath ಅನ್ನು ಓದಲು, ನೋಡಲು ಮತ್ತು ಬಳಸಲು ಸುಲಭವಾಗುವಂತೆ ಹೊಂದಿಸಿ.","Normal text":"ಸಾಮಾನ್ಯ ಪಠ್ಯ","Larger text":"ದೊಡ್ಡ ಪಠ್ಯ","Extra-large text":"ಬಹಳ ದೊಡ್ಡ ಪಠ್ಯ","High contrast":"ಹೆಚ್ಚಿನ ಕಾಂಟ್ರಾಸ್ಟ್","Reduce motion":"ಚಲನೆಯನ್ನು ಕಡಿಮೆ ಮಾಡಿ","Underline links":"ಲಿಂಕ್‌ಗಳಿಗೆ ಕೆಳಗೆ ರೇಖೆ","Reset settings":"ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಮರುಹೊಂದಿಸಿ"}}
let settings={...defaults};
let lang=localStorage.getItem(LANG_KEY)||"en";
try{settings={...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{}
const t=k=>labels[lang]?.[k]||labels.en[k];
function save(){localStorage.setItem(KEY,JSON.stringify(settings));}
function apply(){document.body.classList.toggle("a11y-large",settings.size==="large");document.body.classList.toggle("a11y-xlarge",settings.size==="xlarge");document.body.classList.toggle("a11y-high-contrast",settings.contrast);document.body.classList.toggle("a11y-reduce-motion",settings.motion);document.body.classList.toggle("a11y-underline",settings.underline);}
function translatePage(){document.documentElement.lang=lang==="hi"?"hi":lang==="kn"?"kn":"en";const map=translations[lang]||{};if(!map)return;const walker=document.createTreeWalker(document.querySelector("#app")||document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(node=>{const key=node.nodeValue.trim();if(map[key])node.nodeValue=node.nodeValue.replace(key,map[key]);});document.querySelectorAll(".prototype-chip").forEach(el=>{if(lang!=="en")el.textContent=lang==="hi"?"सिंथेटिक सार्वजनिक-सेवा प्रोटोटाइप":"ಸಿಂಥೆಟಿಕ್ ಸಾರ್ವಜನಿಕ-ಸೇವಾ ಮಾದರಿ"});}
function ensurePanel(){if(document.querySelector(".accessibility-trigger"))return;const wrap=document.createElement("div");wrap.innerHTML=`<button class="accessibility-trigger" type="button" aria-label="Open accessibility options" aria-expanded="false" data-a11y-open>♿</button><section class="accessibility-panel" hidden aria-label="Accessibility options"><button class="accessibility-close" type="button" aria-label="Close accessibility options" data-a11y-close>×</button><h2>Accessibility options</h2><p>Adjust CarePath to make the journey easier to read, see and use.</p><div class="accessibility-options"><button class="accessibility-option" data-a11y-size="normal">Normal text</button><button class="accessibility-option" data-a11y-size="large">Larger text</button><button class="accessibility-option" data-a11y-size="xlarge">Extra-large text</button><button class="accessibility-option" data-a11y-contrast>High contrast</button><button class="accessibility-option" data-a11y-motion>Reduce motion</button><button class="accessibility-option" data-a11y-underline>Underline links</button></div><button class="accessibility-reset" type="button" data-a11y-reset>Reset settings</button></section>`;document.body.appendChild(wrap);}
function ensureNav(){const top=document.querySelector(".top-actions");if(!top||top.querySelector(".carepath-nav-tools"))return;const wrap=document.createElement("div");wrap.className="carepath-nav-tools";wrap.innerHTML=`<button class="nav-tool" type="button" data-nav-a11y aria-haspopup="dialog">♿ <span>${t("access")}</span></button><label class="nav-language"><span class="sr-only">${t("language")}</span><select data-nav-language aria-label="${t("language")}"><option value="en">EN</option><option value="hi">हिं</option><option value="kn">ಕನ್ನಡ</option></select></label><button class="nav-tool nav-voice" type="button" data-nav-voice>🔊 <span>${t("voice")}</span></button>`;top.prepend(wrap);}
function syncNav(){const sel=document.querySelector("[data-nav-language]");if(sel)sel.value=lang;const a=document.querySelector("[data-nav-a11y] span");if(a)a.textContent=t("access");const v=document.querySelector("[data-nav-voice] span");if(v)v.textContent=t("voice");const l=document.querySelector(".nav-language .sr-only");if(l)l.textContent=t("language");if(sel)sel.setAttribute("aria-label",t("language"));}
function sync(){apply();ensurePanel();ensureNav();document.querySelectorAll("[data-a11y-size]").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.a11ySize===settings.size)));document.querySelector("[data-a11y-contrast]")?.setAttribute("aria-pressed",String(settings.contrast));document.querySelector("[data-a11y-motion]")?.setAttribute("aria-pressed",String(settings.motion));document.querySelector("[data-a11y-underline]")?.setAttribute("aria-pressed",String(settings.underline));syncNav();translatePage();}
document.addEventListener("click",e=>{const open=e.target.closest?.("[data-a11y-open]"),close=e.target.closest?.("[data-a11y-close]"),panel=document.querySelector(".accessibility-panel");if(open){panel.hidden=false;open.setAttribute("aria-expanded","true");return}if(close){panel.hidden=true;document.querySelector("[data-a11y-open]")?.setAttribute("aria-expanded","false");return}const size=e.target.closest?.("[data-a11y-size]");if(size){settings.size=size.dataset.a11ySize;save();sync();return}if(e.target.closest?.("[data-a11y-contrast]")){settings.contrast=!settings.contrast;save();sync();return}if(e.target.closest?.("[data-a11y-motion]")){settings.motion=!settings.motion;save();sync();return}if(e.target.closest?.("[data-a11y-underline]")){settings.underline=!settings.underline;save();sync();return}if(e.target.closest?.("[data-a11y-reset]")){settings={...defaults};save();sync();return}if(e.target.closest?.("[data-nav-a11y]")){document.querySelector("[data-a11y-open]")?.click();return}if(e.target.closest?.("[data-nav-voice]")){if(!window.speechSynthesis)return;if(speechSynthesis.speaking){speechSynthesis.cancel();return}const main=document.querySelector("main");if(!main)return;const text=[...main.querySelectorAll("h1,h2,h3,p,b,strong,button,li")].map(x=>x.innerText.trim()).filter(Boolean).join(". ");const u=new SpeechSynthesisUtterance(text);u.lang=lang==="hi"?"hi-IN":lang==="kn"?"kn-IN":"en-IN";u.rate=.92;speechSynthesis.speak(u);return}});
document.addEventListener("change",e=>{if(e.target.matches?.("[data-nav-language]")){lang=e.target.value;localStorage.setItem(LANG_KEY,lang);syncNav();translatePage();}});
window.addEventListener("hashchange",()=>setTimeout(()=>{syncNav();translatePage();},60));
setTimeout(sync,0);
