const KEY="carepath:accessibility:v3";
const LANG_KEY="carepath:language:v3";
const defaults={size:"normal",contrast:false,motion:false,underline:false};
const labels={en:{access:"Accessibility",language:"Language",voice:"Read aloud"},hi:{access:"सुलभता",language:"भाषा",voice:"पढ़कर सुनाएँ"},kn:{access:"ಪ್ರವೇಶಸಾಧ್ಯತೆ",language:"ಭಾಷೆ",voice:"ಓದಿ ಕೇಳಿಸಿ"}};
let settings={...defaults};
let lang=localStorage.getItem(LANG_KEY)||"en";
try{settings={...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{}
const t=k=>labels[lang]?.[k]||labels.en[k];
function save(){localStorage.setItem(KEY,JSON.stringify(settings));}
function apply(){document.body.classList.toggle("a11y-large",settings.size==="large");document.body.classList.toggle("a11y-xlarge",settings.size==="xlarge");document.body.classList.toggle("a11y-high-contrast",settings.contrast);document.body.classList.toggle("a11y-reduce-motion",settings.motion);document.body.classList.toggle("a11y-underline",settings.underline);}
function ensurePanel(){if(document.querySelector(".accessibility-trigger"))return;const wrap=document.createElement("div");wrap.innerHTML=`<button class="accessibility-trigger" type="button" aria-label="Open accessibility options" aria-expanded="false" data-a11y-open>♿</button><section class="accessibility-panel" hidden aria-label="Accessibility options"><button class="accessibility-close" type="button" aria-label="Close accessibility options" data-a11y-close>×</button><h2>Accessibility options</h2><p>Adjust CarePath to make the journey easier to read, see and use.</p><div class="accessibility-options"><button class="accessibility-option" data-a11y-size="normal">Normal text</button><button class="accessibility-option" data-a11y-size="large">Larger text</button><button class="accessibility-option" data-a11y-size="xlarge">Extra-large text</button><button class="accessibility-option" data-a11y-contrast>High contrast</button><button class="accessibility-option" data-a11y-motion>Reduce motion</button><button class="accessibility-option" data-a11y-underline>Underline links</button></div><button class="accessibility-reset" type="button" data-a11y-reset>Reset settings</button></section>`;document.body.appendChild(wrap);}
function ensureNav(){const top=document.querySelector(".top-actions");if(!top||top.querySelector(".carepath-nav-tools"))return;const wrap=document.createElement("div");wrap.className="carepath-nav-tools";wrap.innerHTML=`<button class="nav-tool" type="button" data-nav-a11y aria-haspopup="dialog">♿ <span>${t("access")}</span></button><label class="nav-language"><span class="sr-only">${t("language")}</span><select data-nav-language aria-label="${t("language")}\"><option value="en">EN</option><option value="hi">हिं</option><option value="kn">ಕನ್ನಡ</option></select></label><button class="nav-tool nav-voice" type="button" data-nav-voice>🔊 <span>${t("voice")}</span></button>`;top.prepend(wrap);}
function syncNav(){const sel=document.querySelector("[data-nav-language]");if(sel)sel.value=lang;const a=document.querySelector("[data-nav-a11y] span");if(a)a.textContent=t("access");const v=document.querySelector("[data-nav-voice] span");if(v)v.textContent=t("voice");const l=document.querySelector(".nav-language .sr-only");if(l)l.textContent=t("language");if(sel)sel.setAttribute("aria-label",t("language"));}
function sync(){apply();ensurePanel();ensureNav();document.querySelectorAll("[data-a11y-size]").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.a11ySize===settings.size)));document.querySelector("[data-a11y-contrast]")?.setAttribute("aria-pressed",String(settings.contrast));document.querySelector("[data-a11y-motion]")?.setAttribute("aria-pressed",String(settings.motion));document.querySelector("[data-a11y-underline]")?.setAttribute("aria-pressed",String(settings.underline));syncNav();}
document.addEventListener("click",e=>{const open=e.target.closest?.("[data-a11y-open]"),close=e.target.closest?.("[data-a11y-close]"),panel=document.querySelector(".accessibility-panel");if(open){panel.hidden=false;open.setAttribute("aria-expanded","true");return}if(close){panel.hidden=true;document.querySelector("[data-a11y-open]")?.setAttribute("aria-expanded","false");return}const size=e.target.closest?.("[data-a11y-size]");if(size){settings.size=size.dataset.a11ySize;save();sync();return}if(e.target.closest?.("[data-a11y-contrast]")){settings.contrast=!settings.contrast;save();sync();return}if(e.target.closest?.("[data-a11y-motion]")){settings.motion=!settings.motion;save();sync();return}if(e.target.closest?.("[data-a11y-underline]")){settings.underline=!settings.underline;save();sync();return}if(e.target.closest?.("[data-a11y-reset]")){settings={...defaults};save();sync();return}if(e.target.closest?.("[data-nav-a11y]")){document.querySelector("[data-a11y-open]")?.click();return}if(e.target.closest?.("[data-nav-voice]")){if(!window.speechSynthesis)return;if(speechSynthesis.speaking){speechSynthesis.cancel();return}const main=document.querySelector("main");if(!main)return;const text=[...main.querySelectorAll("h1,h2,h3,p,b,strong,button,li")].map(x=>x.innerText.trim()).filter(Boolean).join(". ");const u=new SpeechSynthesisUtterance(text);u.lang=lang==="hi"?"hi-IN":lang==="kn"?"kn-IN":"en-IN";u.rate=.92;speechSynthesis.speak(u);return}});
document.addEventListener("change",e=>{if(e.target.matches?.("[data-nav-language]")){lang=e.target.value;localStorage.setItem(LANG_KEY,lang);syncNav();}});
setTimeout(sync,0);
