const KEY="carepath:accessibility:v1";
const defaults={size:"normal",contrast:false,motion:false,underline:false};
let settings={...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")};
function save(){localStorage.setItem(KEY,JSON.stringify(settings));}
function apply(){document.body.classList.toggle("a11y-large",settings.size==="large");document.body.classList.toggle("a11y-xlarge",settings.size==="xlarge");document.body.classList.toggle("a11y-high-contrast",settings.contrast);document.body.classList.toggle("a11y-reduce-motion",settings.motion);document.body.classList.toggle("a11y-underline",settings.underline);}
function panel(){if(document.querySelector(".accessibility-trigger"))return;const wrap=document.createElement("div");wrap.innerHTML=`<button class="accessibility-trigger" type="button" aria-label="Open accessibility options" aria-expanded="false" data-a11y-open>♿</button><section class="accessibility-panel" hidden aria-label="Accessibility options"><button class="accessibility-close" type="button" aria-label="Close accessibility options" data-a11y-close>×</button><h2>Accessibility options</h2><p>Adjust CarePath to make the journey easier to read, see and use.</p><div class="accessibility-options"><button class="accessibility-option" data-a11y-size="normal">Normal text</button><button class="accessibility-option" data-a11y-size="large">Larger text</button><button class="accessibility-option" data-a11y-size="xlarge">Extra-large text</button><button class="accessibility-option" data-a11y-contrast>High contrast</button><button class="accessibility-option" data-a11y-motion>Reduce motion</button><button class="accessibility-option" data-a11y-underline>Underline links</button></div><button class="accessibility-reset" type="button" data-a11y-reset>Reset settings</button></section>`;document.body.appendChild(wrap);}
function sync(){apply();document.querySelectorAll("[data-a11y-size]").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.a11ySize===settings.size)));document.querySelector("[data-a11y-contrast]")?.setAttribute("aria-pressed",String(settings.contrast));document.querySelector("[data-a11y-motion]")?.setAttribute("aria-pressed",String(settings.motion));document.querySelector("[data-a11y-underline]")?.setAttribute("aria-pressed",String(settings.underline));}
document.addEventListener("click",e=>{const open=e.target.closest?.("[data-a11y-open]");const close=e.target.closest?.("[data-a11y-close]");const panelEl=document.querySelector(".accessibility-panel");if(open){panelEl.hidden=false;open.setAttribute("aria-expanded","true");return}if(close){panelEl.hidden=true;document.querySelector("[data-a11y-open]")?.setAttribute("aria-expanded","false");return}const size=e.target.closest?.("[data-a11y-size]");if(size){settings.size=size.dataset.a11ySize;save();sync();return}if(e.target.closest?.("[data-a11y-contrast]")){settings.contrast=!settings.contrast;save();sync();return}if(e.target.closest?.("[data-a11y-motion]")){settings.motion=!settings.motion;save();sync();return}if(e.target.closest?.("[data-a11y-underline]")){settings.underline=!settings.underline;save();sync();return}if(e.target.closest?.("[data-a11y-reset]")){settings={...defaults};save();sync();return}});
panel();sync();
