/* CarePath stable shell. Navbar stays outside #app. */
(() => {
  const LANG_KEY="carepath:language:v3", A11Y_KEY="carepath:accessibility:v3", AUTH_KEY="carepath:role:v6";
  const app=document.querySelector("#app");
  const labels={en:{access:"Accessibility",voice:"Read aloud",home:"Home",logout:"Log out"},hi:{access:"सुलभता",voice:"पढ़कर सुनाएँ",home:"होम",logout:"लॉग आउट"},kn:{access:"ಪ್ರವೇಶಸಾಧ್ಯತೆ",voice:"ಓದಿ ಕೇಳಿಸಿ",home:"ಮುಖಪುಟ",logout:"ಲಾಗ್ ಔಟ್"}};
  let lang=localStorage.getItem(LANG_KEY)||"en";
  let settings={size:"normal",contrast:false,motion:false,underline:false};
  try{settings={...settings,...JSON.parse(localStorage.getItem(A11Y_KEY)||"{}")}catch{}
  const save=()=>localStorage.setItem(A11Y_KEY,JSON.stringify(settings));
  const apply=()=>{document.body.classList.toggle("a11y-large",settings.size==="large");document.body.classList.toggle("a11y-xlarge",settings.size==="xlarge");document.body.classList.toggle("a11y-high-contrast",!!settings.contrast);document.body.classList.toggle("a11y-reduce-motion",!!settings.motion);document.body.classList.toggle("a11y-underline",!!settings.underline)};
  function shell(){const l=labels[lang]||labels.en,role=sessionStorage.getItem(AUTH_KEY);return `<header id="carepath-shell" class="topbar carepath-stable-shell"><a class="brand" href="#/services" aria-label="CarePath home"><span class="brand-mark">+</span>CarePath</a><span class="prototype-chip">SYNTHETIC PUBLIC-SERVICE PROTOTYPE</span><nav class="carepath-shell-nav" aria-label="CarePath controls"><button class="shell-tool" type="button" data-shell-a11y>♿ <span>${l.access}</span></button><label class="shell-language"><span class="sr-only">Language</span><select data-shell-language aria-label="Language"><option value="en" ${lang==="en"?"selected":""}>EN</option><option value="hi" ${lang==="hi"?"selected":""}>हिन्दी</option><option value="kn" ${lang==="kn"?"selected":""}>ಕನ್ನಡ</option></select></label><button class="shell-tool" type="button" data-shell-read>${l.voice}</button>${role?`<span class="role-chip">${role==="staff"?"Staff simulator":"Patient journey"}</span><button class="ghost-button" data-shell-logout type="button">${l.logout}</button>`:`<button class="icon-button" data-shell-home type="button" aria-label="${l.home}">⌂</button>`}</nav></header>`}
  function render(){if(!document.body)return;const old=document.querySelector("#carepath-shell");if(old)old.outerHTML=shell();else document.body.insertAdjacentHTML("afterbegin",shell());apply();app?.querySelectorAll(":scope > .topbar").forEach(e=>{e.hidden=true;e.setAttribute("aria-hidden","true")})}
  function setLanguage(next){lang=next==="hi"||next==="kn"?next:"en";localStorage.setItem(LANG_KEY,lang);document.documentElement.lang=lang;render();window.dispatchEvent(new CustomEvent("carepath:language-changed",{detail:{lang}}))}
  function a11y(){let p=document.querySelector("#carepath-stable-a11y");if(!p){p=document.createElement("section");p.id="carepath-stable-a11y";p.className="stable-a11y-panel";p.setAttribute("role","dialog");p.innerHTML=`<div class="stable-a11y-head"><div><span class="eyebrow">CAREPATH</span><h2>Accessibility</h2></div><button type="button" data-a11y-close>×</button></div><p>Adjust the journey to make it easier to read, see and use.</p><div class="stable-a11y-options"><button type="button" data-a11y-size="normal">Normal text</button><button type="button" data-a11y-size="large">Larger text</button><button type="button" data-a11y-size="xlarge">Extra-large text</button><button type="button" data-a11y-contrast>High contrast</button><button type="button" data-a11y-motion>Reduce motion</button><button type="button" data-a11y-underline>Underline links</button></div><button class="secondary-button" type="button" data-a11y-reset>Reset settings</button>`;document.body.appendChild(p)}p.hidden=false}
  document.addEventListener("click",e=>{const x=e.target.closest("[data-shell-a11y],[data-shell-read],[data-shell-home],[data-shell-logout],[data-a11y-close],[data-a11y-reset],[data-a11y-size],[data-a11y-contrast],[data-a11y-motion],[data-a11y-underline]");if(!x)return;if(x.matches("[data-shell-a11y]")){a11y();return}if(x.matches("[data-shell-read]")){const t=document.querySelector("#app main")?.innerText||document.body.innerText;if("speechSynthesis"in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t.slice(0,5000)))}return}if(x.matches("[data-shell-home]")){location.hash="/services";return}if(x.matches("[data-shell-logout]")){sessionStorage.removeItem(AUTH_KEY);location.hash="/services";render();return}if(x.matches("[data-a11y-close]")){const p=document.querySelector("#carepath-stable-a11y");if(p)p.hidden=true;return}if(x.matches("[data-a11y-size]"))settings.size=x.dataset.a11ySize;if(x.matches("[data-a11y-contrast]"))settings.contrast=!settings.contrast;if(x.matches("[data-a11y-motion]"))settings.motion=!settings.motion;if(x.matches("[data-a11y-underline]"))settings.underline=!settings.underline;if(x.matches("[data-a11y-reset]"))settings={size:"normal",contrast:false,motion:false,underline:false};save();apply()});
  document.addEventListener("change",e=>{if(e.target.matches("[data-shell-language]"))setLanguage(e.target.value)});
  window.addEventListener("hashchange",render);
  document.documentElement.lang=lang;render();
})();
