const CP_STAFF_STEPS=["Appointment","Arrive","Registration","Called","Consultation","Lab","Pharmacy","Complete"];
const CP_STAFF_KEY="carepath:staff:patients:v2";
const CP_ROLE_KEY="carepath:role:v6";
const CP_EVENT={PATIENT_ARRIVED:"PATIENT_ARRIVED",CHECKED_IN:"CHECKED_IN",QUEUE_ADVANCED:"QUEUE_ADVANCED",ROOM_CHANGED:"ROOM_CHANGED",CALL_PATIENT:"CALL_PATIENT",START_CONSULTATION:"START_CONSULTATION",COMPLETE_CONSULTATION:"COMPLETE_CONSULTATION",COMPLETE_LAB:"COMPLETE_LAB",COMPLETE_PHARMACY:"COMPLETE_PHARMACY"};
const CP_STATUS={APPOINTMENT_CONFIRMED:"Appointment confirmed",ARRIVED:"Arrived",WAITING:"Waiting",CALLED:"Called",CONSULTATION:"Consultation",LAB:"Lab",PHARMACY:"Pharmacy",COMPLETED:"Completed"};
const CP_DEFAULT_PATIENTS=[
{id:"DEMO-042",name:"Ravi Kumar",token:"42",state:"APPOINTMENT_CONFIRMED",doctor:"Dr. Mehta",room:"202",queueAhead:null,appointment:"10:30 AM",updated:"10:12 AM",hold:false},
{id:"DEMO-043",name:"Priya Shah",token:"43",state:"WAITING",doctor:"Dr. Mehta",room:"204",queueAhead:2,appointment:"10:40 AM",updated:"10:15 AM",hold:false},
{id:"DEMO-044",name:"Arjun Mehta",token:"44",state:"WAITING",doctor:"Dr. Mehta",room:"204",queueAhead:3,appointment:"10:50 AM",updated:"10:16 AM",hold:false},
{id:"DEMO-045",name:"Neha Rao",token:"45",state:"ARRIVED",doctor:"Dr. Mehta",room:"202",queueAhead:null,appointment:"11:00 AM",updated:"10:18 AM",hold:false},
{id:"DEMO-046",name:"Karan Singh",token:"46",state:"CALLED",doctor:"Dr. Mehta",room:"204",queueAhead:0,appointment:"11:10 AM",updated:"10:20 AM",hold:false},
{id:"DEMO-047",name:"Ananya Das",token:"47",state:"CONSULTATION",doctor:"Dr. Mehta",room:"204",queueAhead:null,appointment:"11:20 AM",updated:"10:21 AM",hold:false},
{id:"DEMO-048",name:"Vikram Patel",token:"48",state:"COMPLETED",doctor:"Dr. Mehta",room:"204",queueAhead:null,appointment:"11:30 AM",updated:"10:05 AM",hold:false}
];
let cpPatients=cpLoadPatients();
let cpSelected="DEMO-042";
let cpView="dashboard";
let cpAssistantNotice="";
function cpStaffRole(){try{return sessionStorage.getItem(CP_ROLE_KEY)==="staff"}catch{return false}}
function cpLoadPatients(){try{const saved=JSON.parse(localStorage.getItem(CP_STAFF_KEY)||"null");if(Array.isArray(saved)&&saved.length===7)return saved}catch{}return structuredClone(CP_DEFAULT_PATIENTS)}
function cpSavePatients(){try{localStorage.setItem(CP_STAFF_KEY,JSON.stringify(cpPatients))}catch{}}
function cpNow(){return new Intl.DateTimeFormat("en-IN",{hour:"numeric",minute:"2-digit"}).format(new Date())}
function cpStatusLabel(p){return CP_STATUS[p.state]||p.state.replaceAll("_"," ")}
function cpStateIndex(p){return ({APPOINTMENT_CONFIRMED:0,ARRIVED:1,WAITING:2,CALLED:3,CONSULTATION:4,LAB:5,PHARMACY:6,COMPLETED:7})[p.state]??0}
function cpSelectedPatient(){return cpPatients.find(p=>p.id===cpSelected)||cpPatients[0]}
function cpQueue(){return [...cpPatients].filter(p=>p.state!=="COMPLETED").sort((a,b)=>Number(a.token)-Number(b.token))}
function cpFindNext(){return cpPatients.find(p=>p.state==="WAITING"&&!p.hold&&p.queueAhead===0)||cpPatients.find(p=>p.state==="WAITING"&&!p.hold)||cpPatients.find(p=>p.state==="ARRIVED"&&!p.hold)}
function cpSetPatient(id,patch){const i=cpPatients.findIndex(p=>p.id===id);if(i<0)return;cpPatients[i]={...cpPatients[i],...patch,updated:cpNow()};cpSavePatients()}
async function cpSyncRavi(type,extra={}){const p=cpSelectedPatient();if(p.id!=="DEMO-042")return;try{const r=await fetch("/api/event",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,...extra,role:"staff"})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Could not update the shared journey.");const j=data.journey;cpSetPatient("DEMO-042",{state:j.state,room:j.room,queueAhead:j.queueAhead,updated:j.lastUpdated});cpAssistantNotice="";cpRender()}catch(e){cpAssistantNotice=e.message;cpRender()}}
function cpAdvanceLocal(p,type){const next={PATIENT_ARRIVED:{state:"ARRIVED",queueAhead:null},CHECKED_IN:{state:"WAITING",queueAhead:Math.max(0,p.queueAhead??3)},QUEUE_ADVANCED:{state:"WAITING",queueAhead:Math.max(0,(p.queueAhead??1)-1)},ROOM_CHANGED:{room:p.room==="202"?"204":"202"},CALL_PATIENT:{state:"CALLED",queueAhead:0},START_CONSULTATION:{state:"CONSULTATION",queueAhead:null},COMPLETE_CONSULTATION:{state:"LAB",queueAhead:null},COMPLETE_LAB:{state:"PHARMACY"},COMPLETE_PHARMACY:{state:"COMPLETED"}}[type];if(next)cpSetPatient(p.id,next)}
function cpNextType(p){return ({APPOINTMENT_CONFIRMED:"arrive",ARRIVED:"register",WAITING:"advance",CALLED:"consult",CONSULTATION:"complete",LAB:"lab",PHARMACY:"pharmacy"})[p.state]||null}
async function cpContextAction(){const p=cpSelectedPatient();const action=cpNextType(p);if(!action)return;if(action==="arrive"){cpAdvanceLocal(p,"PATIENT_ARRIVED");if(p.id==="DEMO-042")return cpSyncRavi(CP_EVENT.PATIENT_ARRIVED,{description:`${p.name} arrived at the hospital`})}if(action==="register"){cpAdvanceLocal(p,"CHECKED_IN");if(p.id==="DEMO-042")return cpSyncRavi(CP_EVENT.CHECKED_IN,{queueAhead:3,description:"Registration completed — Ravi joined the queue"})}if(action==="advance"){cpAdvanceLocal(p,"QUEUE_ADVANCED");if(p.id==="DEMO-042")return cpSyncRavi(CP_EVENT.QUEUE_ADVANCED,{description:"Queue advanced"})}if(action==="consult"){cpAdvanceLocal(p,"START_CONSULTATION");if(p.id==="DEMO-042")return cpSyncRavi(CP_EVENT.START_CONSULTATION,{description:"Patient moved into consultation"})}if(action==="complete"){cpAdvanceLocal(p,"COMPLETE_CONSULTATION");if(p.id==="DEMO-042")return cpSyncRavi(CP_EVENT.COMPLETE_CONSULTATION,{description:"Consultation completed — lab is next"})}if(action==="lab"){cpAdvanceLocal(p,"COMPLETE_LAB");if(p.id==="DEMO-042")return cpSyncRavi(CP_EVENT.COMPLETE_LAB,{description:"Lab step completed — pharmacy is next"})}if(action==="pharmacy"){cpAdvanceLocal(p,"COMPLETE_PHARMACY");if(p.id==="DEMO-042")return cpSyncRavi(CP_EVENT.COMPLETE_PHARMACY,{description:"Pharmacy step completed — visit done"})}cpRender()}
function cpAction(type){const selected=cpSelectedPatient();if(type==="call"){const next=selected.state==="WAITING"&&selected.queueAhead===0&&!selected.hold?selected:cpFindNext();if(!next){cpAssistantNotice="No patient is ready to be called.";return cpRender()}cpSelected=next.id;cpAdvanceLocal(next,"CALL_PATIENT");if(next.id==="DEMO-042")return cpSyncRavi(CP_EVENT.CALL_PATIENT,{description:`Token ${next.token} called to Room ${next.room}`});return cpRender()}if(type==="room"){const room=selected.room==="202"?"204":"202";cpAdvanceLocal(selected,"ROOM_CHANGED");if(selected.id==="DEMO-042")return cpSyncRavi(CP_EVENT.ROOM_CHANGED,{room,description:`Consultation room changed from ${selected.room} to ${room}`});return cpRender()}if(type==="hold"){cpSetPatient(selected.id,{hold:!selected.hold});return cpRender()}if(type==="complete"){if(selected.state!=="CONSULTATION"){cpAssistantNotice="Complete consultation becomes available when this patient is in consultation.";return cpRender()}return cpContextAction()}if(type==="sms"){cpAssistantNotice=`SMS preview: ${cpSms(selected)}`;return cpRender()}}
function cpSms(p){if(p.state==="WAITING")return `CAREPATH: Token ${p.token}. Orthopaedics, Room ${p.room}. ${p.queueAhead??0} ahead.`;if(p.state==="CALLED")return `CAREPATH: Your turn. Token ${p.token}, go to Room ${p.room} now.`;if(p.state==="COMPLETED")return "CAREPATH: Your Orthopaedics visit is complete. Thank you.";return `CAREPATH: Appointment ${p.id} confirmed. Bring your appointment ID to OPD Block A.`}
function cpPatientJourney(p){const i=cpStateIndex(p);return `<div class="cp-staff-rail">${CP_STAFF_STEPS.map((s,n)=>`<div class="${n<i?"done ":n===i?"current ":""}"><span>${n<i?"✓":n+1}</span><small>${s}</small></div>`).join("")}</div>`}
function cpPatientRows(list){return list.map(p=>`<button class="cp-patient-row ${p.id===cpSelected?"selected":""}" data-patient="${p.id}"><span class="cp-token">${p.token}</span><span class="cp-patient-name"><b>${p.name}</b><small>${p.id} · ${p.appointment}</small></span><span class="cp-patient-status ${p.hold?"hold":""}">${p.hold?"On hold":cpStatusLabel(p)}</span><span class="cp-patient-room">Room ${p.room}</span></button>`).join("")}
function cpActionCard(p){const context=cpNextType(p);const labels={arrive:"Mark arrived",register:"Complete registration",advance:"Advance queue",consult:"Start consultation",complete:"Complete consultation",lab:"Complete lab",pharmacy:"Complete pharmacy"};return `<article class="cp-staff-card cp-action-card"><div class="cp-card-title"><span>ACTIONS</span><b>Update the journey</b></div><div class="cp-context-action">${context?`<button data-cp-context>${labels[context]} <span>→</span></button>`:"<span>Visit complete</span>"}</div><div class="cp-staff-actions"><button data-cp-staff="call">Call next patient <span>→</span></button><button data-cp-staff="room">Change room <span>→</span></button><button data-cp-staff="hold" class="hold-action">${p.hold?"Resume patient":"Hold / pause"} <span>→</span></button><button data-cp-staff="complete">Complete consultation <span>→</span></button><button data-cp-staff="sms" class="muted">Send SMS update <span>→</span></button></div></article>`}
function cpDashboard(){const p=cpSelectedPatient();const waiting=cpPatients.filter(x=>x.state==="WAITING"&&!x.hold).length;const called=cpPatients.filter(x=>x.state==="CALLED"&&!x.hold).length;const completed=cpPatients.filter(x=>x.state==="COMPLETED").length;return `<div class="cp-dashboard"><div class="cp-metric-grid"><div><span>WAITING</span><strong>${waiting}</strong><small>patients in queue</small></div><div><span>CALLED</span><strong>${called}</strong><small>ready for consultation</small></div><div><span>COMPLETED</span><strong>${completed}</strong><small>visits today</small></div></div><div class="cp-staff-grid"><article class="cp-staff-card cp-state-card"><div class="cp-card-title"><span>CURRENT VISIT</span><b>${p.name}</b></div><div class="cp-patient-meta">${p.id} · Token ${p.token} · ${p.appointment}</div><div class="cp-staff-stats"><div><small>Status</small><strong>${p.hold?"On hold":cpStatusLabel(p)}</strong></div><div><small>Doctor</small><strong>${p.doctor}</strong></div><div><small>Room</small><strong>${p.room}</strong></div><div><small>Token</small><strong>${p.token}</strong></div></div></article>${cpActionCard(p)}</div><section class="cp-staff-journey"><div class="cp-card-title"><span>PATIENT JOURNEY</span><b>Same journey, staff side</b></div>${cpPatientJourney(p)}</section><section class="cp-staff-card cp-queue-preview"><div class="cp-card-title"><span>TODAY'S QUEUE</span><b>7 synthetic patients</b></div>${cpPatientRows(cpQueue().slice(0,5))}<button class="cp-inline-link" data-nav="queue">View full queue →</button></section></div>`}
function cpQueueView(){return `<section class="cp-page-section"><div class="cp-section-head"><div><span>QUEUE</span><h3>Today's Orthopaedics queue</h3><p>Every record here is synthetic. Select a patient to update the visit.</p></div><strong>${cpPatients.filter(p=>p.state!=="COMPLETED").length} active</strong></div><div class="cp-queue-table">${cpPatientRows(cpQueue())}</div></section>`}
function cpPatientsView(){return `<section class="cp-page-section"><div class="cp-section-head"><div><span>PATIENTS</span><h3>Today's patients</h3><p>Synthetic appointment and journey information only.</p></div><strong>${cpPatients.length} patients</strong></div><div class="cp-queue-table">${cpPatientRows(cpPatients)}</div></section>`}
function cpAnnouncementsView(){const items=cpPatients.filter(p=>p.state==="CALLED"||p.hold||p.state==="LAB"||p.state==="COMPLETED").map(p=>p.hold?[`${p.name} is on hold`,`Token ${p.token} · Staff action paused the journey.`,"Hold"]:p.state==="CALLED"?[`Call ${p.name} to Room ${p.room}`,`Token ${p.token} is ready for consultation.`,"Next"]:p.state==="LAB"?[`${p.name} moved to lab`,`Consultation is complete; lab is next.`,"Journey"]:[`${p.name} completed the visit`,`Token ${p.token} · Journey complete.`,"Done"]);return `<section class="cp-page-section"><div class="cp-section-head"><div><span>ANNOUNCEMENTS</span><h3>What's changed</h3><p>Operational updates generated from this synthetic demo.</p></div></div><div class="cp-announcements">${(items.length?items:[["No new updates","The desk is ready for the next patient.","Ready"]]).map(([t,b,badge])=>`<article><span>${badge}</span><div><b>${t}</b><p>${b}</p></div><time>${cpNow()}</time></article>`).join("")}</div></section>`}
function cpSettingsView(){return `<section class="cp-page-section"><div class="cp-section-head"><div><span>SETTINGS</span><h3>Staff desk</h3><p>Prototype settings — no real hospital data is stored.</p></div></div><div class="cp-settings"><div><b>Department</b><span>Orthopaedics OPD</span></div><div><b>Doctor</b><span>Dr. Mehta</span></div><div><b>Queue mode</b><span>Live synthetic demo</span></div><button data-reset-staff>Reset synthetic patients</button></div></section>`}
function cpRender(){const shell=document.querySelector(".cp-staff-command");if(!shell)return;const views={dashboard:cpDashboard,queue:cpQueueView,patients:cpPatientsView,announcements:cpAnnouncementsView,settings:cpSettingsView};shell.querySelector(".cp-staff-content").innerHTML=views[cpView]();shell.querySelectorAll("[data-patient]").forEach(b=>b.addEventListener("click",()=>{cpSelected=b.dataset.patient;cpView="dashboard";cpAssistantNotice="";cpRender()}));shell.querySelectorAll("[data-nav]").forEach(b=>b.addEventListener("click",()=>{cpView=b.dataset.nav;cpRender()}));shell.querySelectorAll("[data-cp-staff]").forEach(b=>b.addEventListener("click",()=>cpAction(b.dataset.cpStaff)));shell.querySelector("[data-cp-context]")?.addEventListener("click",()=>cpContextAction());shell.querySelector("[data-reset-staff]")?.addEventListener("click",()=>{cpPatients=structuredClone(CP_DEFAULT_PATIENTS);cpSavePatients();cpSelected="DEMO-042";cpAssistantNotice="Synthetic patients reset.";cpRender()});shell.querySelectorAll("[data-staff-nav]").forEach(b=>b.classList.toggle("active",b.dataset.staffNav===cpView));const n=shell.querySelector(".cp-staff-notice");n.hidden=!cpAssistantNotice;n.textContent=cpAssistantNotice}
function cpStaffView(){if(!cpStaffRole()||document.querySelector(".cp-staff-command"))return;const shell=document.createElement("section");shell.className="cp-staff-command";shell.innerHTML=`<aside class="cp-staff-sidebar"><div class="cp-staff-hospital"><span>✚</span><div><b>City Government<br>Hospital</b><small>Orthopaedics OPD</small></div></div><nav><button data-staff-nav="dashboard" class="active">⌂ <span>Dashboard</span></button><button data-staff-nav="queue">◷ <span>Queue</span></button><button data-staff-nav="patients">♙ <span>Patients</span></button><button data-staff-nav="announcements">◌ <span>Announcements</span></button><button data-staff-nav="settings">⚙ <span>Settings</span></button></nav><p>All data is synthetic.</p></aside><div class="cp-staff-main"><div class="cp-staff-top"><div><p>STAFF PANEL · SYNTHETIC</p><h2>Good morning, Staff.</h2><span>Help desk · Orthopaedics · Dr. Mehta</span></div><div class="cp-staff-user">STAFF-ORTHO <b>●</b></div></div><div class="cp-staff-notice" hidden></div><div class="cp-staff-content"></div></div>`;document.querySelector("#app").prepend(shell);shell.querySelectorAll("[data-staff-nav]").forEach(b=>b.addEventListener("click",()=>{cpView=b.dataset.staffNav;cpAssistantNotice="";cpRender()}));cpRender();cpHideLegacyStaff()}
function cpHideLegacyStaff(){document.querySelector("#staff-view")?.setAttribute("hidden","true");document.querySelectorAll(".staff-view,.staff-simulator,.simulator-section").forEach(e=>e.setAttribute("hidden","true"))}
function cpRefreshStaff(){document.querySelector(".cp-staff-command")?.remove();cpStaffView()}
window.addEventListener("DOMContentLoaded",()=>setTimeout(cpStaffView,120));
window.addEventListener("hashchange",()=>setTimeout(()=>{if(cpStaffRole())cpRefreshStaff()},180));
window.addEventListener("storage",e=>{if(e.key===CP_STAFF_KEY){cpPatients=cpLoadPatients();cpRender()}});
setTimeout(cpStaffView,250);
